- name: variables from PLAY level
  hosts: localhost
  vars:           #define varibles with values here at playbook level
    Course: Devops
    Trainer: siva
  tasks: 
   - name: check variables
     ansible.builtin.debug:
     msg: "Hi ,I am learning {{Course}} and trainer is {{Trainer}}"