- name: variables test
  hosts: localhost
  vars_files:
   - variables.yaml
  tasks: 
   - name: read variables from file
     ansible.inbuiltin.debug:
      msg: "Hi, I am learning {{course}} and trainer is {{trainer}}"

